const {Router} = require('express');

const router = Router();

const admin = require('firebase-admin');

const generarQR= require('qrcode');

const serviceAccount = require("../../tesis-459e4-firebase-adminsdk-rgg32-053fff63bc.json");
admin.initializeApp({
    credential: admin.credential.cert(serviceAccount), databaseURL:'https://tesis-459e4-default-rtdb.firebaseio.com/'
});


const db = admin.database();

const ref=db.ref('Lugar');



router.get('/', (req,res)=>{
    ref.once('value',(snapshot)=>{
        const data = snapshot.val();
        res.render('index',{Lugar:data});
    });
});

router.post('/nuevo-marcador', (req,res)=>{
    const newPostRef =ref.push();

    // Get the unique key generated by push()
    const postId = newPostRef.key;
    
    var lugares = req.body.lugares;
    if(lugares==null){
        lugares="";
    }
    console.log(lugares);
    const nuevoMarcador={
        id: postId,
        nombre: req.body.nombre,
        latitud: req.body.latitud,
        longitud: req.body.longitud,
        lugares: lugares
    };

    newPostRef.set(nuevoMarcador);
    //newPostRef.push(nuevoMarcador);
    console.log(postId);
    console.log(req.body);
    res.redirect('/');
});

router.get('/eliminar-marcador/:id',(req,res)=>{
    db.ref('Lugar/'+req.params.id).remove();    
    console.log(req.params.id);
    res.redirect('/');
});

router.get('/editar-marcador/:id',(req,res)=>{
    lugar_id=req.params.id;
    ref.once('value',(snapshot)=>{
        const lugareall = snapshot.val();
        getID(lugar_id).then(data=>{
            res.render('editar-marcador',{
            id:data.id,
            nombre:data.nombre,
            latitud:data.latitud,
            longitud:data.longitud, 
            lugares:data.lugares,
            Lugar:lugareall});
        });
    });
});
router.post('/editar-marcador/:id',(req,res)=>{
    var lugar_id=req.params.id;
    var lugares = req.body.lugares;
    if(lugares==null){
        lugares="";
    }
    console.log(lugares);
    const nuevoMarcador={
        id: lugar_id,
        nombre: req.body.nombre,
        latitud: req.body.latitud,
        longitud: req.body.longitud,
        lugares: lugares
    };

    db.ref('Lugar/'+lugar_id).update(nuevoMarcador);


    console.log(req.params.id);
    console.log(req.body);
    res.redirect('/');
});

router.get('/crear-marcador',(req,res)=>{
    ref.once('value',(snapshot)=>{
        const data = snapshot.val();
        res.render('crear-marcador',{Lugar:data});
    });
});


router.get('/generarQR/:id',(req,res)=>{
    const qrID=req.params.id;
    generarQR.toDataURL(qrID,{ version: 5 },function(err,url){
        if(err) res.send('Código QR no disponible')
        console.log(url);
        res.render('codigoQR',{
            QR:url,});
    })
});


// GET BLOG DATA
function getID(lugarid){
	const reflugar = admin.database().ref('Lugar/'+lugarid);
	return reflugar.once('value').then(snap => snap.val());
}


module.exports=router;